In [2]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

# Need to turn off the cache, or the spreadsheet will only get
# reloaded after cache expiration, usually 4 hours. This should be triggered by the
# -n option to mp, but the option isn't passed into IPython notebook execution. 
from metapack import Downloader
downloader = Downloader.get_instance()
downloader.use_cache = False

In [3]:
#pkg = mp.jupyter.open_package()
pkg = mp.jupyter.open_source_package()
pkg

# COVID-19 Cases For San Diego County
`sandiegodata.org-covid19-1.2.1` Last Update: 2020-03-26T03:17:29

_Cases, deaths, hospitalizations and other data scraped from the San Diego COunty COVID-19 website._


This dataset is manually extracted from the daily updates to the [San Diego
County Coronavirus Disease 2019
(COVID-19)](https://www.sandiegocounty.gov/coronavirus/) web page. The table on
the web page is pulled into a [Google
Spreadsheet](https://docs.google.com/spreadsheets/d/1RkgOAgmZIcq7WdNvxn4dih_-aX6
im3fNd9yrfM1-0Ys/edit?usp=sharing), and this dataset extracts the Summary tab
of the Google spreadsheet.

## Caveats

* The County changes the table format ocassionally, often adding columns, to not all variables are available for all dates.
* This dataset does not include the information for age groups that is available in the source tables.
* The `cases` value for March 14 is created by interpolating ( exponential ) from the values before and after it.




## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [sd_covid_cases](notebooks/Process.ipynb#df)**. Notebook for creating dataset.

## References
<ul><li> <strong><a href="https://docs.google.com/spreadsheets/d/1RkgOAgmZIcq7WdNvxn4dih_-aX6im3fNd9yrfM1-0Ys/edit#gid=1588490640">spreadsheet</a></strong>. Google spreadsheet, for humans</li><li> <strong>source</string>, <em>gs:1RkgOAgmZIcq7WdNvxn4dih_-aX6im3fNd9yrfM1-0Ys#1588490640</em>. Machine readable source file</li><ul>

In [4]:
df = pkg.reference('source').dataframe()
df.tail()

,date,Cases,Cases_Male,Cases_Female,Hospitalized,Intensive Care,Deaths,Notes
9,2020-03-21,159,104.0,54.0,34.0,13.0,0.0,NaN
10,2020-03-22,205,133.0,71.0,41.0,15.0,1.0,NaN
11,2020-03-23,230,145.0,84.0,37.0,18.0,1.0,NaN
12,2020-03-24,242,157.0,85.0,45.0,21.0,2.0,NaN
13,2020-03-25,297,185.0,12.0,59.0,29.0,2.0,NaN